name: Deploy Frontend

on:
  push:
    branches: [ master ]
    paths:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml

    # Step 3: Install PNPM
    - name: Install PNPM 
      run: npm install -g pnpm

    # Step 4: Install dependencies
    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    # Step 5: Setup SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 6: Add host to known hosts
    - name: Add host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    # Step 7: Backup current deployment
    - name: Backup current deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/rosantibike/frontend
          if [ -d ".next" ]; then
            tar -czf backup_$(date +%Y%m%d_%H%M%S).tar.gz .next
            mv backup_*.tar.gz /var/www/backups/
          fi

    # Step 8: Deploy new version
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory
          cd /var/www/rosantibike/frontend
          
          # Pull latest changes
          git fetch origin master
          git reset --hard origin/master
          
          # Install dependencies
          echo "Installing dependencies..."
          pnpm install --frozen-lockfile --prod
          
          # Build application
          echo "Building application..."
          pnpm run build
          
          # Restart application
          echo "Restarting application..."
          if pm2 list | grep -q "rental-frontend"; then
            pm2 restart rental-frontend
          else
            pm2 start pnpm --name "rental-frontend" -- start
          fi
          
          # Save PM2 process list
          pm2 save
          
          # Log deployment
          echo "Deployment completed at $(date)" >> /var/www/rosantibike/deploy.log

    # Step 9: Verify deployment
    - name: Verify deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Check if application is running
          if pm2 list | grep -q "rental-frontend" && pm2 list | grep "rental-frontend" | grep -q "online"; then
            echo "Application is running successfully"
            exit 0
          else
            echo "Application failed to start"
            exit 1
          fi

    # Step 10: Cleanup old backups
    - name: Cleanup old backups
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Keep only last 5 backups
          cd /var/www/backups
          ls -t backup_*.tar.gz | tail -n +6 | xargs -r rm 