name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup ESLint
      run: |
        npm install --save-dev eslint eslint-config-next
        if [ ! -f .eslintrc.json ]; then
          echo '{
            "extends": "next/core-web-vitals",
            "rules": {
              "react/no-unescaped-entities": "off",
              "react-hooks/exhaustive-deps": "warn",
              "@next/next/no-img-element": "warn"
            }
          }' > .eslintrc.json
        else
          node -e "
            const fs = require('fs');
            const config = JSON.parse(fs.readFileSync('.eslintrc.json', 'utf8'));
            config.rules = config.rules || {};
            config.rules['react/no-unescaped-entities'] = 'off';
            config.rules['react-hooks/exhaustive-deps'] = 'warn';
            config.rules['@next/next/no-img-element'] = 'warn';
            fs.writeFileSync('.eslintrc.json', JSON.stringify(config, null, 2));
          "
        fi
      
    - name: Run linting
      run: npm run lint || true
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          .eslintrc.json
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-deps-

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          .eslintrc.json
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies if needed
      run: test -d node_modules || npm ci
      
    - name: Build project
      run: npm run build
    
    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: |
          .next
          public
        key: ${{ runner.os }}-build-${{ github.sha }}

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: |
          .next
          public
        key: ${{ runner.os }}-build-${{ github.sha }}
        
    - name: Restore dependency cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          .eslintrc.json
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        
    - name: Update package.json
      run: |
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          pkg.devDependencies = pkg.devDependencies || {};
          pkg.devDependencies.eslint = pkg.devDependencies.eslint || '^8.56.0';
          pkg.devDependencies['eslint-config-next'] = pkg.devDependencies['eslint-config-next'] || '^14.0.4';
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "
        
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    - name: Deploy to VPS
      run: |
        # Pastikan .eslintrc.json ada
        if [ ! -f .eslintrc.json ]; then
          echo '{
            "extends": "next/core-web-vitals",
            "rules": {
              "react/no-unescaped-entities": "off",
              "react-hooks/exhaustive-deps": "warn",
              "@next/next/no-img-element": "warn"
            }
          }' > .eslintrc.json
        fi
        
        # Compress files before transfer to reduce bandwidth
        tar -czf deploy.tar.gz .next package.json ecosystem.config.js .eslintrc.json public
        
        # Transfer compressed file (faster than individual files)
        scp deploy.tar.gz root@141.11.25.200:/var/www/rosantibike/
        
        # Extract and restart on server
        ssh root@141.11.25.200 "cd /var/www/rosantibike && tar -xzf deploy.tar.gz && rm deploy.tar.gz && npm ci --omit=dev && pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js"
    
    - name: Send notification on success
      if: success()
      run: echo "Deployment berhasil!"
    
    - name: Send notification on failure
      if: failure()
      run: echo "Deployment gagal!" 