name: Deploy ke VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Konfigurasi ESLint
        run: |
          if [ ! -f .eslintrc.json ]; then
            echo '{
              "extends": "next/core-web-vitals",
              "rules": {
                "react/no-unescaped-entities": "off",
                "react-hooks/exhaustive-deps": "warn",
                "@next/next/no-img-element": "warn"
              }
            }' > .eslintrc.json
          fi
      
      - name: Lint kode
        run: npm run lint || true
      
      - name: Build aplikasi
        run: npm run build
      
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Tambahkan host ke known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy ke VPS
        env:
          SSH_USER: root
          SSH_HOST: ${{ secrets.SERVER_IP }}
        run: |
          # Kompres untuk deployment
          tar -czf deploy.tar.gz .next/ package.json package-lock.json public/ ecosystem.config.js .eslintrc.json

          # Transfer ke VPS
          scp deploy.tar.gz $SSH_USER@$SSH_HOST:/tmp/
          
          # Buat script deployment
          cat > deploy.sh << 'EOFSCRIPT'
          #!/bin/bash
          mkdir -p /var/www/rosantibikemotorent/frontend
          
          tar -xzf /tmp/deploy.tar.gz -C /var/www/rosantibikemotorent/frontend
          
          cd /var/www/rosantibikemotorent/frontend
          npm ci --omit=dev
          
          if pm2 list | grep -q "rosantibike-frontend"; then
            pm2 reload ecosystem.config.js
          else
            pm2 start ecosystem.config.js
          fi
          
          pm2 save
          
          rm /tmp/deploy.tar.gz
          
          echo "Frontend deployed at $(date)" >> /var/www/rosantibikemotorent/deploy.log
          EOFSCRIPT
          
          # Transfer script ke VPS
          scp deploy.sh $SSH_USER@$SSH_HOST:/tmp/
          
          # Jalankan script di VPS
          ssh $SSH_USER@$SSH_HOST "chmod +x /tmp/deploy.sh && /tmp/deploy.sh && rm /tmp/deploy.sh"
      
      - name: Notifikasi sukses
        if: success()
        run: echo "Deployment berhasil pada $(date)"
      
      - name: Notifikasi gagal
        if: failure()
        run: echo "Deployment gagal pada $(date)" 